#!/usr/bin/env bash
# initialize.sh — connect Hermes to a WAHA instance and verify access.
# ONE entry point. Idempotent.
#
# Usage:
#   WAHA_URL=https://your-waha.example API_KEY=xxx bash initialize.sh
#   bash initialize.sh --url https://... --key xxx
#   bash initialize.sh --session all-in-one-device
set -euo pipefail

WAHA_URL="${WAHA_URL:-}"
API_KEY="${API_KEY:-}"
SESSION="${SESSION:-all-in-one-device}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --url) WAHA_URL="$2"; shift 2 ;;
    --key) API_KEY="$2"; shift 2 ;;
    --session) SESSION="$2"; shift 2 ;;
    -h|--help) sed -n '2,12p' "$0"; exit 0 ;;
    *) echo "Unknown arg: $1" >&2; exit 2 ;;
  esac
done

[[ -z "$WAHA_URL" ]] && { echo "ERROR: butuh --url atau WAHA_URL env var." >&2; exit 1; }
[[ -z "$API_KEY" ]] && { echo "ERROR: butuh --key atau API_KEY env var." >&2; exit 1; }

# Hapus trailing slash
WAHA_URL="${WAHA_URL%/}"

section() { printf '\n\033[1;36m━━ %s ━━\033[0m\n' "$1"; }
ok()      { printf '  \033[1;32m✓\033[0m %s\n' "$1"; }
warn()    { printf '  \033[1;33m⚠\033[0m %s\n' "$1"; }
fail()    { printf '  \033[1;31m✗\033[0m %s\n' "$1"; }

# Simpan config ke ~/.waha-marketing/config.env supaya script lain bisa baca
CFG_DIR="${WAHA_CONFIG_DIR:-$HOME/.waha-marketing}"
mkdir -p "$CFG_DIR"
cat > "$CFG_DIR/config.env" <<EOF
# Auto-generated by waha-marketing skill initialize.sh
WAHA_URL="$WAHA_URL"
WAHA_API_KEY="$API_KEY"
WAHA_SESSION="$SESSION"
EOF
chmod 600 "$CFG_DIR/config.env"   # api key is sensitive
ok "Config saved: $CFG_DIR/config.env (chmod 600)"

section "1/4  Cek WAHA server reachable"
CODE=$(curl -s -o /dev/null -w "%{http_code}" "$WAHA_URL/health" \
       -H "X-Api-Key: $API_KEY" --max-time 10 || echo "000")
if [[ "$CODE" == "200" ]]; then
  ok "WAHA server reachable, health OK"
else
  fail "WAHA server health check failed (HTTP $CODE). Cek --url dan --key."
  exit 1
fi

section "2/4  Cek WAHA version + tier"
VER=$(curl -s "$WAHA_URL/" -H "X-Api-Key: $API_KEY" --max-time 10 2>/dev/null || \
      curl -s "$WAHA_URL/api/version" -H "X-Api-Key: $API_KEY" --max-time 10 2>/dev/null || echo "{}")
echo "$VER" | python3 -c "
import sys, json
try:
    d = json.loads(sys.stdin.read())
    print(f'  \033[1;32m✓\033[0m version: {d.get(\"version\",\"?\")}, engine: {d.get(\"engine\",\"?\")}, tier: {d.get(\"tier\",\"?\")}')
except: print('  \033[1;33m⚠\033[0m tidak bisa parse version response')
"

section "3/4  Cek session '$SESSION'"
SESS=$(curl -s "$WAHA_URL/api/sessions/$SESSION" -H "X-Api-Key: $API_KEY" --max-time 10 2>/dev/null)
STATUS=$(echo "$SESS" | python3 -c "import sys,json; print(json.load(sys.stdin).get('status','?'))" 2>/dev/null || echo "?")
if [[ "$STATUS" == "WORKING" ]]; then
  ok "Session '$SESSION': WORKING"
  ME=$(curl -s "$WAHA_URL/api/sessions/$SESSION/me" -H "X-Api-Key: $API_KEY" --max-time 10 2>/dev/null)
  echo "$ME" | python3 -c "
import sys,json
d=json.load(sys.stdin)
print(f'  \033[1;32m✓\033[0m akun: {d.get(\"pushName\",\"?\")} ({d.get(\"id\",\"?\")})')
" 2>/dev/null || warn "tidak bisa ambil info akun"
elif [[ "$STATUS" == "FAILED" || "$STATUS" == "STOPPED" ]]; then
  fail "Session '$SESSION' status: $STATUS. Hubungi admin WAHA atau scan QR ulang."
  echo "  Lihat dashboard WAHA untuk QR code: $WAHA_URL"
  exit 1
else
  warn "Session '$SESSION' status: $STATUS (unexpected). Lanjut dengan hati-hati."
fi

section "4/4  Cek labels (butuh WhatsApp Business account)"
LBL=$(curl -s "$WAHA_URL/api/$SESSION/labels" -H "X-Api-Key: $API_KEY" --max-time 10 2>/dev/null)
NL=$(echo "$LBL" | python3 -c "import sys,json; print(len(json.load(sys.stdin)))" 2>/dev/null || echo "0")
if [[ "$NL" -gt 0 ]]; then
  ok "Labels tersedia: $NL (WhatsApp Business)"
else
  warn "Tidak ada labels. Labels butuh WhatsApp Business app (bukan WhatsApp biasa)."
fi

printf '\n\033[1;32m━━ Selesai ━━\033[0m\n'
cat <<DONE
  WAHA:       $WAHA_URL
  Session:    $SESSION (WORKING)
  Config:     $CFG_DIR/config.env

  Perintah berikutnya:
    bash scripts/waha.sh status           ringkasan akun + sessions
    bash scripts/waha.sh groups           list grup
    bash scripts/waha.sh contacts --limit 20  list kontak
    bash scripts/broadcast-helper.sh --help   broadcast (humanized, anti-ban)
    bash scripts/doctor.sh                diagnose kalau ada masalah

  ⚠  INI PRODUKSI. Jangan pernah broadcast tanpa opt-in eksplisit.
  ⚠  Baca references/anti-ban.md sebelum kirim apa-apa.
DONE
