#!/usr/bin/env bash
# initialize.sh — connect Hermes to a mailbox over IMAP + SMTP, and verify both.
# ONE entry point. Idempotent. Sends nothing to anyone.
#
# Gmail (paling umum):
#   bash initialize.sh --email kamu@gmail.com --app-password "abcd efgh ijkl mnop"
#
# Google Workspace (domain sendiri):
#   bash initialize.sh --email kamu@bisnis.com --app-password "..." --provider workspace
#
# Provider lain (Zoho, Fastmail, cPanel, dll):
#   bash initialize.sh --email kamu@domain.com --app-password "..." \
#     --imap-host imap.zoho.com --smtp-host smtp.zoho.com --provider other
#
# App Password Gmail butuh 2-Step Verification aktif:
#   https://myaccount.google.com/apppasswords
# Detail lengkap: references/gmail-setup.md
set -euo pipefail

EMAIL="${EMAIL_ADDRESS:-}"
APP_PW="${EMAIL_APP_PASSWORD:-}"
NAME="${EMAIL_DISPLAY_NAME:-}"
PROVIDER="gmail"
IMAP_HOST=""
SMTP_HOST=""
IMAP_PORT="993"
SMTP_PORT="587"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --email)         EMAIL="$2"; shift 2 ;;
    --app-password)  APP_PW="$2"; shift 2 ;;
    --name)          NAME="$2"; shift 2 ;;
    --provider)      PROVIDER="$2"; shift 2 ;;
    --imap-host)     IMAP_HOST="$2"; shift 2 ;;
    --smtp-host)     SMTP_HOST="$2"; shift 2 ;;
    --imap-port)     IMAP_PORT="$2"; shift 2 ;;
    --smtp-port)     SMTP_PORT="$2"; shift 2 ;;
    -h|--help)       sed -n '2,22p' "$0"; exit 0 ;;
    *) echo "Argumen tidak dikenal: $1" >&2; exit 2 ;;
  esac
done

section() { printf '\n\033[1;36m━━ %s ━━\033[0m\n' "$1"; }
ok()      { printf '  \033[1;32m✓\033[0m %s\n' "$1"; }
warn()    { printf '  \033[1;33m⚠\033[0m %s\n' "$1"; }
fail()    { printf '  \033[1;31m✗\033[0m %s\n' "$1"; }

[[ -z "$EMAIL" ]]  && { echo "ERROR: butuh --email" >&2; exit 1; }
[[ -z "$APP_PW" ]] && { echo "ERROR: butuh --app-password" >&2; exit 1; }

case "$PROVIDER" in
  gmail|workspace)
    IMAP_HOST="${IMAP_HOST:-imap.gmail.com}"
    SMTP_HOST="${SMTP_HOST:-smtp.gmail.com}"
    ;;
  *)
    [[ -z "$IMAP_HOST" || -z "$SMTP_HOST" ]] && {
      echo "ERROR: provider '$PROVIDER' butuh --imap-host dan --smtp-host" >&2; exit 1; }
    ;;
esac

# App password Gmail ditulis dengan spasi di layar Google. Spasinya bukan bagian
# dari password — orang sering menyalin apa adanya lalu bingung kenapa ditolak.
APP_PW_CLEAN="${APP_PW// /}"
if [[ "$PROVIDER" == "gmail" || "$PROVIDER" == "workspace" ]]; then
  if [[ ${#APP_PW_CLEAN} -ne 16 ]]; then
    warn "App Password Gmail biasanya 16 karakter; punyamu ${#APP_PW_CLEAN}."
    warn "Kalau ini password akun biasa, IMAP akan menolak. Lihat references/gmail-setup.md."
  fi
fi

CFG_DIR="${HERMES_EMAIL_CONFIG_DIR:-${HERMES_HOME:-$HOME}/.hermes-email}"
mkdir -p "$CFG_DIR/state"
umask 077
cat > "$CFG_DIR/config.env" <<EOF
# Auto-generated by ibras-email-marketing skill initialize.sh
EMAIL_ADDRESS="$EMAIL"
EMAIL_APP_PASSWORD="$APP_PW_CLEAN"
EMAIL_DISPLAY_NAME="$NAME"
EMAIL_PROVIDER="$PROVIDER"
IMAP_HOST="$IMAP_HOST"
IMAP_PORT="$IMAP_PORT"
SMTP_HOST="$SMTP_HOST"
SMTP_PORT="$SMTP_PORT"
EOF
chmod 600 "$CFG_DIR/config.env"

section "1/4  Simpan config"
ok "Tersimpan: $CFG_DIR/config.env (chmod 600 — hanya kamu yang bisa baca)"
warn "File ini berisi app password. Jangan commit ke git, jangan kirim ke siapa pun."

section "2/4  Cek IMAP + SMTP (tidak mengirim apa pun)"
SKILL_DIR="$(cd "$(dirname "$0")/.." && pwd)"
python3 "$SKILL_DIR/scripts/lib/mailbox.py" test || {
  fail "Koneksi gagal. Jalankan: bash scripts/doctor.sh"
  exit 1
}

section "3/4  Siapkan folder data bersama"
BIZ_DIR="${HERMES_BUSINESS_DIR:-${HERMES_HOME:-$HOME/.hermes}/business}"
mkdir -p "$BIZ_DIR"
ok "Folder data: $BIZ_DIR"
if [[ -f "$BIZ_DIR/faq.yaml" ]]; then
  ok "faq.yaml sudah ada"
else
  warn "faq.yaml belum ada — balasan otomatis belum bisa jalan."
  echo "     cp $SKILL_DIR/templates/faq.example.yaml $BIZ_DIR/faq.yaml"
  echo "     lalu isi dengan pertanyaan yang MEMANG berulang di inbox kamu."
fi

section "4/4  Cek dependensi"
python3 -c "import yaml" 2>/dev/null && ok "PyYAML tersedia" || {
  warn "PyYAML belum ada (dibutuhkan untuk faq.yaml): pip3 install pyyaml"; }

printf '\n\033[1;32m━━ Selesai ━━\033[0m\n'
cat <<DONE
  Akun:     $EMAIL
  IMAP:     $IMAP_HOST:$IMAP_PORT
  SMTP:     $SMTP_HOST:$SMTP_PORT
  Config:   $CFG_DIR/config.env

  Langkah berikutnya:
    bash scripts/mail.sh stats                 ringkasan kotak surat
    bash scripts/mail.sh list --unread         email yang belum dibaca
    bash scripts/autoreply.sh scan             mana yang bisa dijawab otomatis
    bash scripts/autoreply.sh validate         periksa faq.yaml
    bash scripts/doctor.sh                     diagnosa kalau ada masalah

  Semua perintah tulis (kirim, hapus, pindah) DRY RUN dulu sampai kamu
  menambahkan --confirm. Itu rem tangan, bukan tembok.
DONE
